# Trameri Infrastructure Services
<VirtualHost *:80>
    ServerName discovery.trameri.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-aas-discovery:8081/
    ProxyPassReverse / http://secured-aas-discovery:8081/
</VirtualHost>

<VirtualHost *:80>
    ServerName aasreg.trameri.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-aas-registry:8080/
    ProxyPassReverse / http://secured-aas-registry:8080/
</VirtualHost>

<VirtualHost *:80>
    ServerName smreg.trameri.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-sm-registry:8080/
    ProxyPassReverse / http://secured-sm-registry:8080/
</VirtualHost>

<VirtualHost *:80>
    ServerName aasenv.trameri.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-aas-env:8081/
    ProxyPassReverse / http://secured-aas-env:8081/
</VirtualHost>

# EuroGoodies Infrastructure Services
<VirtualHost *:80>
    ServerName discovery.eurogoodies.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-aas-discovery-3:8081/
    ProxyPassReverse / http://secured-aas-discovery-3:8081/
</VirtualHost>

<VirtualHost *:80>
    ServerName aasreg.eurogoodies.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-aas-registry-eurogoodies:8080/
    ProxyPassReverse / http://secured-aas-registry-eurogoodies:8080/
</VirtualHost>

<VirtualHost *:80>
    ServerName smreg.eurogoodies.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-sm-registry-3:8080/
    ProxyPassReverse / http://secured-sm-registry-3:8080/
</VirtualHost>

<VirtualHost *:80>
    ServerName aasenv.eurogoodies.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://secured-aas-env-eurogoodies:8081/
    ProxyPassReverse / http://secured-aas-env-eurogoodies:8081/
</VirtualHost>

# Infrastructure 2 Services
<VirtualHost *:80>
    ServerName discovery.infra2.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://aas-discovery-infra2:8081/
    ProxyPassReverse / http://aas-discovery-infra2:8081/
</VirtualHost>

<VirtualHost *:80>
    ServerName aasreg.infra2.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://aas-registry-infra2:8080/
    ProxyPassReverse / http://aas-registry-infra2:8080/
</VirtualHost>

<VirtualHost *:80>
    ServerName smreg.infra2.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://sm-registry-infra2:8080/
    ProxyPassReverse / http://sm-registry-infra2:8080/
</VirtualHost>

<VirtualHost *:80>
    ServerName aasenv.infra2.basyx.localhost
    ProxyPreserveHost On
    ProxyPass / http://aas-env-infra2:8081/
    ProxyPassReverse / http://aas-env-infra2:8081/
</VirtualHost>
