FROM keycloak/keycloak:24.0.4

# Copy SSL certificates
COPY certs/*.crt /tmp/

# Import SSL certificates into Java cacerts
USER root
RUN for cert in /tmp/*.crt; do \
    alias=$(basename "$cert" .crt); \
    keytool -import -trustcacerts -noprompt \
    -alias "$alias" \
    -file "$cert" \
    -cacerts \
    -storepass changeit; \
    done && \
    rm /tmp/*.crt

USER 1000
