services:
  # Identity provider (Keycloak) for infrastructure 3
  keycloak-eurogoodies:
    build:
      context: ..
      dockerfile: shared-dockerfiles/Dockerfile.keycloak
    image: keycloak-eurogoodies:ssl
    container_name: keycloak-eurogoodies
    extra_hosts:
      - "keycloak-broker.basyx.localhost:host-gateway"
      - "keycloak.trameri.basyx.localhost:host-gateway"
      - "keycloak.eurogoodies.basyx.localhost:host-gateway"
    environment:
      VIRTUAL_HOST: keycloak.eurogoodies.basyx.localhost
      VIRTUAL_PORT: "8080"
      VIRTUAL_PROTO: http
      KC_HOSTNAME: keycloak.eurogoodies.basyx.localhost
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak-admin
      KC_HEALTH_ENABLED: "true"
      KC_IMPORT: /opt/keycloak/data/import/
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    ports:
      - 9098:8080
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    networks:
      - multiple-infrastructures
      
  # Healthcheck for Keycloak service
  keycloak-eurogoodies-healthcheck:
    image: curlimages/curl:latest
    container_name: keycloak-eurogoodies-healthcheck
    command: >
      sh -c "
        echo 'Waiting for Keycloak Infra3 to become ready...';
        until curl -sf http://keycloak-eurogoodies:8080/health/ready; do
          sleep 5;
        done;
        echo 'Keycloak Infra3 is ready!'"
    depends_on:
      - keycloak-eurogoodies
    networks:
      - multiple-infrastructures

  # Infrastructure 3 AAS Discovery service
  aas-discovery-eurogoodies:
    build:
      context: ..
      dockerfile: shared-dockerfiles/Dockerfile.aas-discovery
    image: basyx-aas-discovery-eurogoodies:ssl
    container_name: secured-aas-discovery-3
    extra_hosts:
      - "keycloak.eurogoodies.basyx.localhost:host-gateway"
    environment:
      VIRTUAL_HOST: discovery.eurogoodies.basyx.localhost
      VIRTUAL_PORT: "8081"
      # Component configuration
      SERVER_PORT: 8081
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: aas-discovery-3
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: mongoAdmin
      SPRING_DATA_MONGODB_PASSWORD: mongoPassword
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: 'GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD'
      # Security configuration
      BASYX_FEATURE_AUTHORIZATION_ENABLED: true
      BASYX_FEATURE_AUTHORIZATION_TYPE: rbac
      BASYX_FEATURE_AUTHORIZATION_JWTBEARERTOKENPROVIDER: keycloak
      BASYX_FEATURE_AUTHORIZATION_RBAC_FILE: file:/application/rbac_rules.json
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies
    volumes:
      - ./rules/aas-discovery-rules.json:/application/rbac_rules.json
    ports:
      - '8184:8081'
    restart: unless-stopped
    depends_on:
      keycloak-eurogoodies-healthcheck:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    networks:
      - multiple-infrastructures

  # Infrastructure 3 AAS Registry service
  aas-registry-eurogoodies:
    build:
      context: ..
      dockerfile: shared-dockerfiles/Dockerfile.aas-registry
    image: basyx-aas-registry-eurogoodies:ssl
    container_name: secured-aas-registry-eurogoodies
    extra_hosts:
      - "keycloak.eurogoodies.basyx.localhost:host-gateway"
      - "keycloak-broker.basyx.localhost:host-gateway"
    ports:
      - "8182:8080"
    environment:
      VIRTUAL_HOST: aasreg.eurogoodies.basyx.localhost
      VIRTUAL_PORT: "8080"
      # Component configuration
      SERVER_PORT: 8080
      SPRING_DATA_MONGODB_URI: mongodb://mongoAdmin:mongoPassword@mongo:27017
      SPRING_DATA_MONGODB_DATABASE: aas-registry-3
      SERVER_SERVLET_CONTEXT_PATH: /
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      # Security configuration
      BASYX_FEATURE_AUTHORIZATION_ENABLED: true
      BASYX_FEATURE_AUTHORIZATION_TYPE: rbac
      BASYX_FEATURE_AUTHORIZATION_JWTBEARERTOKENPROVIDER: keycloak
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies
      BASYX_FEATURE_AUTHORIZATION_RBAC_FILE: file:/workspace/config/rbac_rules.json
    volumes:
      - ./rules/aas-registry-rules.json:/workspace/config/rbac_rules.json
    restart: unless-stopped
    depends_on:
      keycloak-eurogoodies-healthcheck:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    networks:
      - multiple-infrastructures

  # Infrastructure 3 Submodel Registry service
  sm-registry-eurogoodies:
    build:
      context: ..
      dockerfile: shared-dockerfiles/Dockerfile.sm-registry
    image: basyx-sm-registry-eurogoodies:ssl
    container_name: secured-sm-registry-3
    extra_hosts:
      - "keycloak.eurogoodies.basyx.localhost:host-gateway"
      - "keycloak-broker.basyx.localhost:host-gateway"
    environment:
      VIRTUAL_HOST: smreg.eurogoodies.basyx.localhost
      VIRTUAL_PORT: "8080"
      # Component configuration
      SERVER_PORT: 8080
      SPRING_DATA_MONGODB_URI: mongodb://mongoAdmin:mongoPassword@mongo:27017
      SPRING_DATA_MONGODB_DATABASE: sm-registry-3
      SERVER_SERVLET_CONTEXT_PATH: /
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      # Security configuration
      BASYX_FEATURE_AUTHORIZATION_ENABLED: true
      BASYX_FEATURE_AUTHORIZATION_TYPE: rbac
      BASYX_FEATURE_AUTHORIZATION_JWTBEARERTOKENPROVIDER: keycloak
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies
      BASYX_FEATURE_AUTHORIZATION_RBAC_FILE: file:/workspace/config/rbac_rules.json
    ports:
      - "8183:8080"
    volumes:
      - ./rules/sm-registry-rules.json:/workspace/config/rbac_rules.json
    restart: unless-stopped
    depends_on:
      keycloak-eurogoodies-healthcheck:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
    networks:
      - multiple-infrastructures

  # Infrastructure 3 AAS Environment service
  aas-env-eurogoodies:
    build:
      context: ..
      dockerfile: shared-dockerfiles/Dockerfile.aas-env
    image: basyx-aas-env-eurogoodies:ssl
    container_name: secured-aas-env-eurogoodies
    extra_hosts:
      - "keycloak.eurogoodies.basyx.localhost:host-gateway"
      - "keycloak-broker.basyx.localhost:host-gateway"
    volumes:
      - ./aas:/application/aas
      - ./rules/aas-env-rules.json:/application/rbac_rules.json
    ports:
      - '8181:8081'
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: aasenv.eurogoodies.basyx.localhost
      VIRTUAL_PORT: "8081"
      # Component configuration
      SERVER_PORT: 8081
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: aas-env-3
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_USERNAME: mongoAdmin
      SPRING_DATA_MONGODB_PASSWORD: mongoPassword
      BASYX_CORS_ALLOWED_ORIGINS: '*'
      BASYX_CORS_ALLOWED_METHODS: 'GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD'
      BASYX_ENVIRONMENT: file:aas
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION: http://aas-discovery-eurogoodies:8081
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://aas-registry-eurogoodies:8080
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION: http://sm-registry-eurogoodies:8080
      BASYX_EXTERNALURL: https://aasenv.eurogoodies.basyx.localhost
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 1024MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 1024MB
      # Security configuration
      BASYX_FEATURE_AUTHORIZATION_ENABLED: true
      BASYX_FEATURE_AUTHORIZATION_TYPE: rbac
      BASYX_FEATURE_AUTHORIZATION_JWTBEARERTOKENPROVIDER: keycloak
      BASYX_FEATURE_AUTHORIZATION_RBAC_FILE: file:/application/rbac_rules.json
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_TOKEN_ENDPOINT: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies/protocol/openid-connect/token
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_CLIENT_ID: workstation-1
      BASYX_AASENVIRONMENT_AUTHORIZATION_PRECONFIGURATION_CLIENT_SECRET: nY0mjyECF60DGzNmQUjL81XurSl8etom
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_ENABLED: true
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_TOKEN_ENDPOINT: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies/protocol/openid-connect/token
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_CLIENT_ID: workstation-1
      BASYX_AASREPOSITORY_FEATURE_DISCOVERYINTEGRATION_AUTHORIZATION_CLIENT_SECRET: nY0mjyECF60DGzNmQUjL81XurSl8etom
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_ENABLED: true
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_TOKEN_ENDPOINT: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies/protocol/openid-connect/token
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_ID: workstation-1
      BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_SECRET: nY0mjyECF60DGzNmQUjL81XurSl8etom
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_ENABLED: true
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_TOKEN_ENDPOINT: https://keycloak.eurogoodies.basyx.localhost/realms/EuroGoodies/protocol/openid-connect/token
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_GRANT_TYPE: CLIENT_CREDENTIALS
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_ID: workstation-1
      BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION_AUTHORIZATION_CLIENT_SECRET: nY0mjyECF60DGzNmQUjL81XurSl8etom
    depends_on:
      keycloak-eurogoodies-healthcheck:
        condition: service_completed_successfully
      mongo:
        condition: service_healthy
      aas-discovery-eurogoodies:
        condition: service_healthy
      aas-registry-eurogoodies:
        condition: service_healthy
      sm-registry-eurogoodies:
        condition: service_healthy
    networks:
      - multiple-infrastructures

networks:
  multiple-infrastructures:
    name: basyx-multi-infrastructures
    driver: bridge
