include:
  - ./Infrastructure1/docker-compose-infra1.yml
  - ./Infrastructure2/docker-compose-infra2.yml
  - ./Infrastructure3/docker-compose-infra3.yml

services:
  # Reverse proxy for all infrastructures
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6.0-alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    environment:
      DEFAULT_HOST: aasgui.trameri.basyx.localhost
      ENABLE_IPV6: "false"
    networks:
      - multiple-infrastructures
  # Common MongoDB service for multiple infrastructures
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    restart: unless-stopped
    healthcheck:
      test: mongo
      interval: 10s
      start_period: 5s
      retries: 5
    networks:
      - multiple-infrastructures

  # Keycloak acting as Identity Broker for infrastructures
  keycloak-broker:
    build:
      context: .
      dockerfile: keycloak-broker/Dockerfile
    container_name: keycloak-broker
    extra_hosts:
      - "keycloak-broker.basyx.localhost:host-gateway"
      - "keycloak.trameri.basyx.localhost:host-gateway"
      - "keycloak.eurogoodies.basyx.localhost:host-gateway"
    environment:
      VIRTUAL_HOST: keycloak-broker.basyx.localhost
      VIRTUAL_PORT: "8080"
      VIRTUAL_PROTO: http
      KC_HOSTNAME: keycloak-broker.basyx.localhost
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak-admin
      KC_HEALTH_ENABLED: "true"
      KC_IMPORT: /opt/keycloak/data/import/
    command: ["start-dev", "--import-realm"]
    restart: unless-stopped
    ports:
      - 9099:8080
    volumes:
      - ./keycloak-broker/realm:/opt/keycloak/data/import
    networks:
      - multiple-infrastructures

  # Common AAS Web UI service for multiple infrastructures
  aas-web-ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    container_name: aas-web-ui
    extra_hosts:
      - "keycloak-broker.basyx.localhost:host-gateway"
    ports:
      - '3000:3000'
    environment:
      VIRTUAL_HOST: aasgui.basyx.localhost
      VIRTUAL_PORT: "3000"
      # Preconfigured default for infrastructure 1
      AAS_REGISTRY_PATH: https://aasreg.trameri.basyx.localhost/shell-descriptors
      SUBMODEL_REGISTRY_PATH: https://smreg.trameri.basyx.localhost/submodel-descriptors
      AAS_REPO_PATH: https://aasenv.trameri.basyx.localhost/shells
      SUBMODEL_REPO_PATH: https://aasenv.trameri.basyx.localhost/submodels
      CD_REPO_PATH: https://aasenv.trameri.basyx.localhost/concept-descriptions
      AAS_DISCOVERY_PATH: https://discovery.trameri.basyx.localhost/lookup/shells
      # Broker Authentication (enabled for cross-infrastructure auth)
      KEYCLOAK_URL: https://keycloak.trameri.basyx.localhost
      KEYCLOAK_REALM: Trameri
      KEYCLOAK_CLIENT_ID: basyx-web-ui
    restart: unless-stopped
    depends_on:
      keycloak-broker:
        condition: service_started
    networks:
      - multiple-infrastructures

  aas-web-ui-2:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    container_name: aas-web-ui-2
    extra_hosts:
      - "keycloak.basyx.localhost:host-gateway"
    ports:
      - '3001:3000'
    environment:
      AAS_REGISTRY_PATH: https://aasreg.trameri.basyx.localhost
      SUBMODEL_REGISTRY_PATH: https://smreg.trameri.basyx.localhost
      AAS_REPO_PATH: https://aasenv.trameri.basyx.localhost
      SUBMODEL_REPO_PATH: hhttps://aasenv.trameri.basyx.localhost
      CD_REPO_PATH: https://aasenv.trameri.basyx.localhost
      AAS_DISCOVERY_PATH: hhttps://discovery.trameri.basyx.localhost
    restart: unless-stopped

networks:
  multiple-infrastructures:
    name: basyx-multi-infrastructures
    driver: bridge
